In [1]:
import tensorflow as tf
import random 

sess = tf.Session()

In [2]:
# The domain of [-1, 1] x [-1, 1] has only 4 possible target functions
# f1(x) = 1
# f2(x) = -1
# f3(x) = x
# f4(x) = -x
targets = [tf.constant([1, 0]), tf.constant([-1, 0]), tf.constant([0, 1]), tf.constant([0, -1])]


In [15]:
def calcNumberItersForConvergance(N, TRIALS):
    sumIters = 0
    sumPErr = 0
    for trial in range(TRIALS):

        t = random.randint(0,3)
        samples = tf.add(tf.scalar_mul(-2, tf.random_uniform([N, 2], 0 , 2, dtype=tf.int32, seed=0)), 1)
        labels = tf.sign(tf.reduce_sum(tf.mul(samples, targets[t]), 1))        

        samplesOut = sess.run(samples)
        labelsOut = sess.run(tf.transpose(labels))
        
        print("Data for trail ", trial, "\n\t The target function coeffecients: ", sess.run(targets[t]), \
              "\n\t The samples: \n", samplesOut, \
              "\n\t The labels: \n", labelsOut)
        
        w = tf.Variable(tf.zeros([2], dtype=tf.int32), name="weights")

        init = tf.initialize_all_variables() 
        sess.run(init)

        iter = 1
        while iter < 7000:
            predicts = tf.sign(tf.reduce_sum(tf.mul(samples, w), 1))

            diff = tf.sub(labels, predicts)

            i = 0
            while i < N:
                dOp = tf.gather(diff, i)
                d = sess.run(dOp)
                if d == 0:
                    i += 1
                else:
                    break

            if i == N:
                break
            else:
                w = tf.add(w, tf.scalar_mul(tf.gather(labels, i), tf.gather(samples, i)))
                weights = sess.run(w)

            if iter % 100 == 0:
                print("iter", '%06d' % (iter), " - weights=", weights)

            iter += 1

        print("Done trial ", '%03d' % trial, " at iteration:", '%06d' % (iter), " - weights=", weights)
        sumIters += iter
        
        errorsT = tf.reduce_sum(tf.abs(tf.sub(labels, tf.sign(tf.reduce_sum(tf.mul(samples, w), 1)))))
        pErrorT = tf.div(tf.to_float(errorsT), N)
        errors = sess.run(errorsT)
        pError = sess.run(pErrorT)
        print("Error at trial ", '%03d' % trial, ":", errors, " - pError=", pError)
        sumPErr += pError

    pMatch = 1 - (sumPErr / TRIALS)
    print("Done all trials for N=", '%03d' % (N), \
          ". The average number of iterations for conversion is ", "{:.9f}".format(sumIters * 1.0 / TRIALS), " - weights=", weights, \
          ". Probability of match: ", pMatch)

In [16]:
calcNumberItersForConvergance(10, 10)





Data for trail  0 
	 The target function coeffecients:  [-1  0] 
	 The samples: 
 [[-1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]] 
	 The labels: 
 [-1 -1 -1 -1  1  1  1  1  1  1]
Done trial  000  at iteration: 000004  - weights= [-3 -1]
Error at trial  000 : 0  - pError= 0.0
Data for trail  1 
	 The target function coeffecients:  [ 0 -1] 
	 The samples: 
 [[-1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]] 
	 The labels: 
 [ 1  1 -1  1 -1  1  1 -1 -1 -1]
Done trial  001  at iteration: 000004  - weights= [-1 -3]
Error at trial  001 : 0  - pError= 0.0
Data for trail  2 
	 The target function coeffecients:  [-1  0] 
	 The samples: 
 [[-1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]] 
	 The labels: 
 [-1 -1 -1 -1  1  1  1  1  1  1]
Done trial  002  at iteration: 000004  - weights= [-3 -1]
Error at trial  002 : 0  - pError= 0.0
Data for trail  3 
	 The target function co

In [17]:
calcNumberItersForConvergance(100, 10)

Data for trail  0 
	 The target function coeffecients:  [1 0] 
	 The samples: 
 [[-1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [ 1 -1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [-1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [ 1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [ 1 -1]
 [ 1  1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [-1  1]
 [ 1  1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1 -1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [ 1 -1]
 [ 1 -1]
 [-1  1]
 [-1  1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1  1]
 [ 1 -1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [ 1 -1]
 [ 1  1]
 [ 1  1]
 [ 1 -1]
 [-1 -1]
 [ 1 -1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [-1  1]] 
	 The labels: 
 [ 

In [18]:
sess.close()